import { Geist, Geist_Mono } from "next/font/google";
// import "@/styles/animate.min.css";
import "@/styles/bootstrap.css";
// import "@/styles/font-awesome.min.css";
// import "@/styles/jquery.datepicker.css";
// import "@/styles/jquery-clockpicker.min.css";
// import "@/styles/lightgallery.min.css";
// import "@/styles/magnific-popup.css";
// import "@/styles/nice-select.css";
// import "@/styles/owl.carousel.min.css";
// import "@/styles/owl.theme.default.min.css";
import "@/styles/style.scss";
import "@/styles/responsive.scss";
import "@/styles/slicknav.min.css";



import 'bootstrap/dist/css/bootstrap.min.css';

import Header from "@/components/header";
import Footer from "@/components/footer";


import '@fortawesome/fontawesome-svg-core/styles.css'; // Import Font Awesome CSS
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false; // Tell Font Awesome to skip adding the CSS automatically

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
